# Parameters used to generate this project with aem-project-archetype

groupId=com.adobe.aem.bootcamp
artifactId=aem-site-bootcamp-w2
version=0.0.1-SNAPSHOT
package=com.adobe.aem.bootcamp
appId=aem-site-bootcamp-w2
appTitle=AEM Site Bootcamp W2
aemVersion=cloud
sdkVersion=latest
languageCountry=${languageCountry}
includeExamples=n
includeErrorHandler=n
frontendModule=general
singleCountry=y
includeDispatcherConfig=y
includeCif=n
includeForms=n
includeFormsenrollment=n
includeFormscommunications=n
sdkFormsVersion=latest
commerceEndpoint=https://hostname.com/graphql
datalayer=y
amp=n
enableDynamicMedia=n
enableSSR=n
precompiledScripts=n
includeFormsheadless=n
